updates from Mitch

diff --git a/checks/lvs_check/run_full_lvs b/checks/lvs_check/run_full_lvs
--- a/checks/lvs_check/run_full_lvs
+++ b/checks/lvs_check/run_full_lvs
@@ -56,11 +56,10 @@ echo "SOURCE FILE(S): $LVS_SPICE_FILES $LVS_VERILOG_FILES"
 echo "TOP LAYOUT: $TOP_LAYOUT"
 echo "LAYOUT FILE: $LAYOUT_FILE"
 
-: "${LVS_ROOT:=$(pwd)}"
 : "${LOG_ROOT:=$(pwd)/$TOP_SOURCE}"
 : "${SIGNOFF_ROOT:=$(pwd)/$TOP_SOURCE}"
 : "${WORK_ROOT:=$(pwd)/$TOP_SOURCE}"
-export LOG_ROOT LVS_ROOT SIGNOFF_ROOT WORK_ROOT
+export LOG_ROOT SIGNOFF_ROOT WORK_ROOT
 
 mkdir -p $LOG_ROOT
 mkdir -p $SIGNOFF_ROOT
@@ -77,7 +76,8 @@ else
 	echo "Tech files do not match:"
 	grep version $PDK_ROOT/$PDK/libs.tech/magic/$PDK.tech $LVS_ROOT/tech/$PDK.tech |
 		awk 'NF > 2'
-	# exit 1
+	echo "Results may be incorrect. Contact efabless to update the soft connection rules."
+	#exit 1
 fi
 
 if [[ ! -f $WORK_ROOT/layout.cells || ! -f $WORK_ROOT/verilog.cells ]]; then
@@ -105,6 +105,7 @@ if [[ -f $WORK_ROOT/layout.cells && -f $WORK_ROOT/verilog.cells ]]; then
 	sed -e 's/\*/.*/g' -e 's/^/^/' -e 's/$/$/' $WORK_ROOT/flatten |
 		grep -f - $WORK_ROOT/layout.cells $WORK_ROOT/verilog.cells |
 		sed 's/.*cells://' |
+		awk 'NF > 0' |
 		sort -u >$WORK_ROOT/flatten.glob
 else
 	cp $WORK_ROOT/flatten $WORK_ROOT/flatten.glob
@@ -118,6 +119,7 @@ if [[ -f $WORK_ROOT/layout.cells && -f $WORK_ROOT/verilog.cells ]]; then
 	sed -e 's/\*/.*/g' -e 's/^/^/' -e 's/$/$/' $WORK_ROOT/noflatten |
 		grep -f - $WORK_ROOT/layout.cells $WORK_ROOT/verilog.cells |
 		sed 's/.*cells://' |
+		awk 'NF > 0' |
 		sort -u >$WORK_ROOT/noflatten.glob
 else
 	cp $WORK_ROOT/noflatten $WORK_ROOT/noflatten.glob
@@ -131,6 +133,7 @@ if [[ -f $WORK_ROOT/layout.cells && -f $WORK_ROOT/verilog.cells ]]; then
 	sed -e 's/\*/.*/g' -e 's/^/^/' -e 's/$/$/' $WORK_ROOT/ignore |
 		grep -f - $WORK_ROOT/layout.cells $WORK_ROOT/verilog.cells |
 		sed 's/.*cells://' |
+		awk 'NF > 0' |
 		sort -u >$WORK_ROOT/ignore.glob
 else
 	cp $WORK_ROOT/noflatten $WORK_ROOT/noflatten.glob
@@ -216,9 +219,11 @@ fi
 #  5. Compare
 echo $LVS_SPICE_FILES |
 	sed 's/  */\n/g' |
+	grep -v '^#' |
 	awk 'NF > 0' >$WORK_ROOT/spice_files
 echo $LVS_VERILOG_FILES |
 	sed 's/  */\n/g' |
+	grep -v '^#' |
 	awk 'NF > 0' >$WORK_ROOT/verilog_files
 
 cp $LVS_ROOT/tech/${PDK}_setup.tcl $WORK_ROOT/${PDK}_setup.tcl
@@ -276,15 +281,11 @@ date "+BEGIN: %c" >$LOG_ROOT/lvs.log
 start_time=$SECONDS
 
 echo " "
+: "${NETGEN_COLUMNS:=80}"
+export NETGEN_COLUMNS
 netgen -batch source $WORK_ROOT/lvs.script 2>&1 |
 	tee -a $LOG_ROOT/lvs.log
 netgen_status=${PIPESTATUS[0]}
-
-if [[ $netgen_status -ne 0 ]]; then
-	echo "
-Error: netgen ended abnormally."
-	exit $netgen_status
-fi
 
 # Check for circuits that were compared as black boxes.
 awk '
@@ -292,10 +293,10 @@ awk '
 /Circuit 2 .* will not flatten/ {print $4, "is a black box in the source"}
 ' $SIGNOFF_ROOT/lvs.report >$SIGNOFF_ROOT/lvs.unflattened
 awk '
-/__fill/ {next}  # ignore abstract devices
+/__fill/ {next} # ignore abstract devices
 /__tapvpwrvgnd/ {next}
 /__fakediode/ {next}
-/sky130_fd_pr__/ {next}  # ignore primitive devices
+/sky130_fd_pr__/ {next} # ignore primitive devices
 /Matching pins/ {print $4, "is a black box in the layout and source"}
 ' $LOG_ROOT/lvs.log >>$SIGNOFF_ROOT/lvs.unflattened
 if [[ -s $SIGNOFF_ROOT/lvs.unflattened ]]; then
@@ -319,11 +320,31 @@ minutes=$(((runtime % 3600) / 60))
 seconds=$(((runtime % 3600) % 60))
 printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >>$LOG_ROOT/lvs.log
 
-# Set exit code if lvs passed conditionally
-if [[ ${lvs_warning:=0} -eq 0 ]]; then
-	exit 0
-else
+# Set exit code
+if [[ $netgen_status -ne 0 ]]; then
+	echo "
+Error: netgen ended abnormally."
+
+# Missing 'Final result' line.
+elif [[ $(grep 'Final result:' $SIGNOFF_ROOT/lvs.report | wc -l) -ne 1 ]]; then
+	netgen_status=4
+	echo "
+Error: netgen did not complete."
+
+# Did not uniquely match.
+elif [[ $(grep 'Final result: Circuits match uniquely\.' $SIGNOFF_ROOT/lvs.report | wc -l) -ne 1 ]]; then
+	netgen_status=4
+	echo "
+Error: LVS mismatch."
+
+# Uniquely matched, but cells were black-boxed or ignored.
+elif [[ ${lvs_warning:=0} -ne 0 ]]; then
+	netgen_status=5
 	echo "
 Warning: possible lvs discrepancy"
-	exit 5
+
+else
+	netgen_status=0
 fi
+
+exit $netgen_status
diff --git a/checks/lvs_check/run_scheck b/checks/lvs_check/run_scheck
--- a/checks/lvs_check/run_scheck
+++ b/checks/lvs_check/run_scheck
@@ -23,6 +23,7 @@
 #  5. Compare
 #
 
+
 # Use cases
 # run_scheck [--noextract] lvs_config_file [top_block [gds_file]]
 
@@ -56,10 +57,11 @@ fi
 if cmp -s $PDK_ROOT/$PDK/libs.tech/magic/$PDK.tech $LVS_ROOT/tech/$PDK.tech; then
 	awk 'NF > 1 && /version/' $LVS_ROOT/tech/$PDK.tech
 else
-	echo "Tech files do not match:"
+	echo "WARNING: Tech files do not match:"
 	grep version $PDK_ROOT/$PDK/libs.tech/magic/$PDK.tech $LVS_ROOT/tech/$PDK.tech |
 		awk 'NF > 2'
-	# exit 1
+	echo "Results may be incorrect. Contact efabless to update the soft connection rules."
+	#exit 1
 fi
 
 CONFIG_FILE=$1
@@ -143,12 +145,12 @@ if [[ $LAYOUT_FILE ]]; then
 
 	export RUN_DIR=$WORK_ROOT/ext
 	echo "Extracting layout with well in background process. See $LOG_ROOT/ext.log."
-	#  1. Extract gds_file with well connectivity
 	(
+		#  1. Extract gds_file with well connectivity
 		date "+BEGIN: %c" >$LOG_ROOT/ext.log
 		start_time=$SECONDS
 		magic -dnull -noc -rcfile $LVS_ROOT/tech/magicrc.well $LVS_ROOT/scripts/gds.$EXT_TYPE.spice.tcl </dev/null >>$LOG_ROOT/ext.log 2>&1
-		#  2. Remove well connections and disconnected nets.; \
+		#  2. Remove well connections and disconnected nets.
 		sed -f $LVS_ROOT/scripts/remove_well.sed $RUN_DIR/$TOP.gds.spice |
 			awk -f $LVS_ROOT/scripts/remove_disconnect.awk - >$RUN_DIR/$TOP.gds.nowell.spice
 		date "+END: %c" >>$LOG_ROOT/ext.log
@@ -161,12 +163,12 @@ if [[ $LAYOUT_FILE ]]; then
 
 	export RUN_DIR=$WORK_ROOT/nowell.ext
 	echo "Extracting layout without well in background process. See $LOG_ROOT/nowell.ext.log."
-	#  3. Extract gds_file without well connectivity
 	(
+		#  3. Extract gds_file without well connectivity
 		date "+BEGIN: %c" >$LOG_ROOT/nowell.ext.log
 		start_time=$SECONDS
 		magic -dnull -noc -rcfile $LVS_ROOT/tech/magicrc.nowell $LVS_ROOT/scripts/gds.$EXT_TYPE.spice.tcl </dev/null >>$LOG_ROOT/nowell.ext.log 2>&1
-		#  4. Remove disconnected nets.; \
+		#  4. Remove disconnected nets.
 		awk -f $LVS_ROOT/scripts/remove_disconnect.awk $RUN_DIR/$TOP.gds.spice >$RUN_DIR/$TOP.gds.nowell.spice
 		date "+END: %c" >>$LOG_ROOT/nowell.ext.log
 		runtime=$((SECONDS - start_time))
@@ -180,6 +182,12 @@ if [[ $LAYOUT_FILE ]]; then
 
 	# Compress large ext files
 	find $WORK_ROOT/*ext -name '*.ext' -size +1M -exec gzip {} \;
+
+	if [[ $(grep 'exttospice finished' $LOG_ROOT/ext.log $LOG_ROOT/nowell.ext.log | wc -l) -ne 2 ]]; then
+		echo "Extraction error: see $LOG_ROOT/ext.log
+and/or $LOG_ROOT/nowell.ext.log"
+		exit 2
+	fi
 else
 	# No gds_file so LVS only. Check for existing extraction results.
 	if [[ ! -f $WORK_ROOT/ext/$TOP.gds.nowell.spice ]]; then
@@ -199,10 +207,20 @@ fi
 #  5. Compare
 date "+BEGIN: %c" >$LOG_ROOT/soft.log
 start_time=$SECONDS
-netgen -batch source $LVS_ROOT/tech/setup_file.soft.lvs | tee -a $LOG_ROOT/soft.log 2>&1
+: "${NETGEN_COLUMNS:=80}"
+export NETGEN_COLUMNS
+netgen -batch source $LVS_ROOT/tech/setup_file.soft.lvs |
+	tee -a $LOG_ROOT/soft.log 2>&1
+scheck_status=${PIPESTATUS[0]}
+if [[ $scheck_status -eq 0 && $(tail $SIGNOFF_ROOT/lvs.soft.report | grep 'Circuits match uniquely\.' | wc -l) -eq 1 ]]; then
+	scheck_status=3
+fi
+
 date "+END: %c" >>$LOG_ROOT/soft.log
 runtime=$((SECONDS - start_time))
 hours=$((runtime / 3600))
 minutes=$(((runtime % 3600) / 60))
 seconds=$(((runtime % 3600) % 60))
 printf "Runtime: %d:%02d:%02d (hh:mm:ss)\n" $hours $minutes $seconds >>$LOG_ROOT/soft.log
+
+exit $scheck_status
